### ISSUE TITLE
More debugging information on initial import

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#282]
It would be useful if we can more easily see the line number in the dump or the exact object that causes an issue, see below output.

```
2020-02-20 17:06:09,762 irrd[24772]: [irrd.mirroring.scheduler#DEBUG] Started new thread Thread-MirrorImportUpdateRunner-LACNIC for mirror import/export for LACNIC
2020-02-20 17:06:09,766 irrd[24772]: [irrd.mirroring.mirror_runners_import#DEBUG] Most recent serial seen for LACNIC: None,force_reload: None, nrtm enabled: True
2020-02-20 17:06:09,766 irrd[24772]: [irrd.mirroring.mirror_runners_import#INFO] Running full import of LACNIC from ['ftp://ftp.lacnic.net/lacnic/irr/LACNIC.CURRENTSERIAL'], serial from ftp://ftp.lacnic.net/lacnic/irr/lacnic.db.gz
2020-02-20 17:06:13,414 irrd[24772]: [irrd.mirroring.mirror_runners_import#ERROR] An exception occurred while attempting a mirror update or initial import for LACNIC: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/irrd_backup/irrd-venv/lib/python3.7/site-packages/irrd/mirroring/mirror_runners_import.py", line 45, in run
    serial_newest_seen=serial_newest_seen, force_reload=force_reload)
  File "/home/irrd_backup/irrd-venv/lib/python3.7/site-packages/irrd/mirroring/mirror_runners_import.py", line 96, in run
    import_serial = int(self._retrieve_file(import_serial_source, return_contents=True)[0])
```

**Comment by mxsasha** [comment]
This is an error in reading the serial number, which should only be one line of ascii. From line 3 that log, it looks like the serial and gzipped dump are reversed in the config. Trying to read a gzip file as a serial number can cause this type of error.
