### ISSUE TITLE
[twisted#ERROR] UnicodeEncodeError: 'ascii' codec can't encode characters in position 546-547: ordinal not in range(128)

### ISSUE THREAD

**Issue by ccaputo** [irrdnet/irrd#286]
**Describe the bug**
Running whois query -g TC:3:34509-LAST on irr.bgp.net.br port 43 resulted in:

```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 546-547: ordinal not in range(128)
```

Full log at: https://gist.github.com/ccaputo/1519fe7a0bc8f9e7f1f29d76e1faeef6

Beginning of query:

```
$ telnet irr.bgp.net.br 43                                                
Trying 18.229.98.198...                                                                  
Connected to bgp.net.br.                                                                 
Escape character is '^]'.                                                                
-g TC:3:34509-LAST                                                                       
%START Version: 3 tc 34509-34589                                                         
                                                                                         
ADD 34509                                                                                
                                                                                         
route:      187.120.176.0/24                                                             
descr:      Prefixo em "Customer Cone" da ENSITE.                                        
origin:     AS262719                                                                     
remarks:    -------------------------------------------------                            
remarks:    Customer Cone - Microdata de Luclia Servios de Provedores Ltda               
remarks:    https://bgp.he.net/AS262719#_graph4                                          
remarks:    Objeto criado para uso em filtros de nossos                                  
remarks:    fornecedores. Se for preciso a remoção deste                                 
remarks:    objeto contacte nosso NOC.                                                   
remarks:    Contacts noc@ensite.com.br
remarks:    Abuse / UCE reports abuse@ensite.com.br
mnt-by:     MAINT-AS28263
changed:    suporte@ensite.com.br 20200224
source:     TC
```

**To Reproduce**
TC config as follows:

```
        TC:
            import_serial_source: 'ftp://ftp.bgp.net.br/dbase/TC.CURRENTSERIAL'
            import_source: 'ftp://ftp.bgp.net.br/dbase/tc.db.gz'
            nrtm_host: irr.bgp.net.br
            import_timer: 300
            object_class_filter:
                - as-set
                - route
                - route6
                - route-set
```

**Expected behaviour**
I would imagine this exception should be caught/handled.

**IRRd version you are running**
Master, as of today.

**Additional context**
Other examples:

```
irrd.utils.whois_client#DEBUG] Running whois query -g RIPE:3:46615766-LAST on rr.ntt.net port 43
[...]
twisted#ERROR] UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 11069: ordinal not in range(128)
```

```
[irrd.utils.whois_client#DEBUG] Running whois query -g RIPE-NONAUTH:3:46615766-LAST on rr.ntt.net port 43
[...]
[twisted#ERROR] UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 30910: ordinal not in range(128)
```

```
2020-02-24 17:59:14,619 irrd[25165]: [twisted#ERROR] --- Logging error ---
2020-02-24 17:59:14,619 irrd[25165]: [twisted#ERROR] Traceback (most recent call last):
2020-02-24 17:59:14,619 irrd[25165]: [twisted#ERROR]   File "/usr/lib64/python3.6/logging/__init__.py", line 996, in emit
2020-02-24 17:59:14,619 irrd[25165]: [twisted#ERROR]     stream.write(msg)
2020-02-24 17:59:14,620 irrd[25165]: [twisted#ERROR] UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 242: ordinal not in range(128)
2020-02-24 17:59:14,620 irrd[25165]: [twisted#ERROR] Call stack:
2020-02-24 17:59:14,620 irrd[25165]: [twisted#ERROR]   File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap
2020-02-24 17:59:14,620 irrd[25165]: [twisted#ERROR]     self._bootstrap_inner()
2020-02-24 17:59:14,621 irrd[25165]: [twisted#ERROR]   File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
2020-02-24 17:59:14,621 irrd[25165]: [twisted#ERROR]     self.run()
2020-02-24 17:59:14,621 irrd[25165]: [twisted#ERROR]   File "/usr/lib64/python3.6/threading.py", line 864, in run
2020-02-24 17:59:14,621 irrd[25165]: [twisted#ERROR]     self._target(*self._args, **self._kwargs)
2020-02-24 17:59:14,621 irrd[25165]: [twisted#ERROR]   File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/mirroring/mirror_runners_import.py", line 47, in run
2020-02-24 17:59:14,622 irrd[25165]: [twisted#ERROR]     self.update_stream_runner.run(serial_newest_seen, database_handler=self.database_handler)
2020-02-24 17:59:14,622 irrd[25165]: [twisted#ERROR]   File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/mirroring/mirror_runners_import.py", line 221, in run
2020-02-24 17:59:14,622 irrd[25165]: [twisted#ERROR]     logger.debug(f'Received NRTM response for {self.source}: {response.strip()}')
2020-02-24 17:59:14,622 irrd[25165]: [twisted#ERROR] Message: 'Received NRTM response for ARIN: %START Version: 3 arin 219011-219011\n\nADD 219011\n\nas-set:         AS-395226-CUSTOMERS\ndescr:          Provides Transit for SCOE\xa0 Customers out of CENIC\nmembers:        AS63398, AS397909\ntech-c:         DUMY-ARIN\nadmin-c:        DUMY-ARIN\nnotify:         networking@scoe.net\nmnt-by:         MNT-SCOE\nchanged:        dkoelzer@scoe.net 20200224\nsource:         ARIN\nremarks:        ****************************\nremarks:        * THIS OBJECT CONTAINS PLACEHOLDER DATA\nremarks:        * Please note that all data that is generally regarded as personal\nremarks:        * data has been removed from this object.\nremarks:        * To view the original object, please query the ARIN Database at:\nremarks:        * http://www.arin.net/whois\nremarks:        ****************************\n\n%END ARIN'
2020-02-24 17:59:14,622 irrd[25165]: [twisted#ERROR] Arguments: ()
```

**Comment by ccaputo** [comment]
In two of the examples above, the relayed data came from another IRRd 4.0 instance running "IRRd -- version 4.0.8".

**Comment by mxsasha** [comment]
It seems that non-ascii characters being logged causes an error. In the environment from which you are starting the irrd process, what are the locale settings (i.e. the output of `locale`)? A possible cause is those not being set to support UTF-8. If that's not it, I'll have to dig a bit deeper. (And if that is the problem, I need to add a note to the documentation.)

**Comment by ccaputo** [comment]
Ahh!  I am starting irrd from root with a "--uid=" arg to drop privs.  I ran locale from the startup script and got:

```
LANG=C                                                                                   
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"            
LC_COLLATE="C"      
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"                             
LC_ADDRESS="C"                                                                           
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

Have now restarted irrd with "export LANG=en_US.UTF-8" to see if that fixes the issue.  Startup script locale output is now:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

This is the Gentoo startup script being used in case helpful to others:  (pid & config location should be adjusted as needed, of course)

```
#!/sbin/openrc-run

export LANG=en_US.UTF-8
command=/home/irrd/irrd-venv/bin/twistd
pidfile=/home/irrd/irrd.pid
command_args="--uid=irrd --pidfile=\"${pidfile}\" irrd --config=/home/irrd/src/config/irrd.yaml"
extra_started_commands="reload"
description_reload="Reload the configuration without exiting"

depend() {
        need postgresql
        provide irrd
}

reload() {
        ebegin "Reloading configuration"
        start-stop-daemon --signal HUP --pidfile "${pidfile}"
        eend $?
}
```

Will report back if the problem continues.  Thanks!

**Comment by ccaputo** [comment]
Reconfirming that after ~2 days, with "export LANG=en_US.UTF-8" in the startup script, none of these errors have reoccurred.
