### ISSUE TITLE
commands following !! are broken

### ISSUE THREAD

**Issue by ccaputo** [irrdnet/irrd#347]
**Describe the bug**
Running today's master (ef416b24a8f1b6a3e82234c796a2dadc7ae52852) with ```!a4AS-ALTOPIA``` at the start of a connection it works fine:

```
$ telnet foo 43
Trying foo...
Connected to foo.
Escape character is '^]'.
!a4AS-ALTOPIA
A64
208.90.168.0/22 208.90.170.0/24 208.90.171.0/24 208.90.168.0/23
C
Connection closed by foreign host.
```

but if I issue it after ```!!``` this happens:

```
$ telnet foo 43
Trying foo...
Connected to foo.
Escape character is '^]'.
!!
!a4AS-ALTOPIA
F An internal error occurred while processing this query.
```

while the log shows:

```
2020-07-06 17:07:01,911 irrd[8682]: [irrd.server.whois.server#DEBUG] 2001:db8::2:40408: processing query: !!
2020-07-06 17:07:01,912 irrd[8682]: [irrd.server.whois.server#INFO] 2001:db8::2:40408: sent answer to query, elapsed 0.00020211189985275269s, 0 bytes: !!
2020-07-06 17:07:02,991 irrd[8682]: [irrd.server.whois.server#DEBUG] 2001:db8::2:40408: processing query: !a4AS-ALTOPIA
2020-07-06 17:07:02,996 irrd[8682]: [irrd.server.whois.query_parser#ERROR] An exception occurred while processing whois query "!a4AS-ALTOPIA": (sqlalchemy.exc.ResourceClosedError) This Connection is closed
[SQL: SELECT rpsl_objects.parsed_data, rpsl_objects.rpsl_pk, rpsl_objects.source, rpsl_objects.object_class 
FROM rpsl_objects 
WHERE rpsl_objects.source IN (%(source_1)s, %(source_2)s, %(source_3)s, %(source_4)s, %(source_5)s, %(source_6)s, %(source_7)s, %(source_8)s, %(source_9)s, %(source_10)s, %(source_11)s, %(source_12)s, %(source_13)s, %(source_14)s, %(source_15)s, %(source_16)s, %(source_17)s, %(source_18)s, %(source_19)s) AND rpsl_objects.object_class IN (%(object_class_1)s
) AND rpsl_objects.rpsl_pk IN (%(rpsl_pk_1)s) ORDER BY CASE WHEN (rpsl_objects.source = %(source_20)s) THEN %(param_1)s WHEN (rpsl_objects.source = %(source_21)s) THEN %(param_2)s WHEN (rpsl_objects.source = %(source_22)s) THEN %(param_3)s WHEN (rpsl_objects.source = %(source_23)s) THEN %(param_4)s WHEN (rpsl_objects.source = %(source_24)s) THEN %(param_5)
s WHEN (rpsl_objects.source = %(source_25)s) THEN %(param_6)s WHEN (rpsl_objects.source = %(source_26)s) THEN %(param_7)s WHEN (rpsl_objects.source = %(source_27)s) THEN %(param_8)s WHEN (rpsl_objects.source = %(source_28)s) THEN %(param_9)s WHEN (rpsl_objects.source = %(source_29)s) THEN %(param_10)s WHEN (rpsl_objects.source = %(source_30)s) THEN %(param
_11)s WHEN (rpsl_objects.source = %(source_31)s) THEN %(param_12)s WHEN (rpsl_objects.source = %(source_32)s) THEN %(param_13)s WHEN (rpsl_objects.source = %(source_33)s) THEN %(param_14)s WHEN (rpsl_objects.source = %(source_34)s) THEN %(param_15)s WHEN (rpsl_objects.source = %(source_35)s) THEN %(param_16)s WHEN (rpsl_objects.source = %(source_36)s) THEN
 %(param_17)s WHEN (rpsl_objects.source = %(source_37)s) THEN %(param_18)s WHEN (rpsl_objects.source = %(source_38)s) THEN %(param_19)s ELSE %(param_20)s END, rpsl_objects.ip_first ASC, rpsl_objects.asn_first ASC, rpsl_objects.rpsl_pk ASC]
Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1209, in _execute_context
    conn = self._revalidate_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 479, in _revalidate_connection
    raise exc.ResourceClosedError("This Connection is closed")
sqlalchemy.exc.ResourceClosedError: This Connection is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/query_parser.py", line 76, in handle_query
    return self.handle_irrd_command(query[1:])
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/query_parser.py", line 148, in handle_irrd_command
    result = self.handle_irrd_routes_for_as_set(parameter)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/query_parser.py", line 231, in handle_irrd_routes_for_as_set
    members = self._recursive_set_resolve({set_name})
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/query_parser.py", line 287, in _recursive_set_resolve
    sub_members, leaf_members = self._find_set_members(members)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/query_parser.py", line 344, in _find_set_members
    query_result = list(self.database_handler.execute_query(query))
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/storage/database_handler.py", line 102, in execute_query
    result = self._connection.execute(statement)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1214, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1209, in _execute_context
    conn = self._revalidate_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 479, in _revalidate_connection
    raise exc.ResourceClosedError("This Connection is closed")
sqlalchemy.exc.StatementError: (sqlalchemy.exc.ResourceClosedError) This Connection is closed
[SQL: SELECT rpsl_objects.parsed_data, rpsl_objects.rpsl_pk, rpsl_objects.source, rpsl_objects.object_class 
FROM rpsl_objects 
WHERE rpsl_objects.source IN (%(source_1)s, %(source_2)s, %(source_3)s, %(source_4)s, %(source_5)s, %(source_6)s, %(source_7)s, %(source_8)s, %(source_9)s, %(source_10)s, %(source_11)s, %(source_12)s, %(source_13)s, %(source_14)s, %(source_15)s, %(source_16)s, %(source_17)s, %(source_18)s, %(source_19)s) AND rpsl_objects.object_class IN (%(object_class_1)s
) AND rpsl_objects.rpsl_pk IN (%(rpsl_pk_1)s) ORDER BY CASE WHEN (rpsl_objects.source = %(source_20)s) THEN %(param_1)s WHEN (rpsl_objects.source = %(source_21)s) THEN %(param_2)s WHEN (rpsl_objects.source = %(source_22)s) THEN %(param_3)s WHEN (rpsl_objects.source = %(source_23)s) THEN %(param_4)s WHEN (rpsl_objects.source = %(source_24)s) THEN %(param_5)
s WHEN (rpsl_objects.source = %(source_25)s) THEN %(param_6)s WHEN (rpsl_objects.source = %(source_26)s) THEN %(param_7)s WHEN (rpsl_objects.source = %(source_27)s) THEN %(param_8)s WHEN (rpsl_objects.source = %(source_28)s) THEN %(param_9)s WHEN (rpsl_objects.source = %(source_29)s) THEN %(param_10)s WHEN (rpsl_objects.source = %(source_30)s) THEN %(param
_11)s WHEN (rpsl_objects.source = %(source_31)s) THEN %(param_12)s WHEN (rpsl_objects.source = %(source_32)s) THEN %(param_13)s WHEN (rpsl_objects.source = %(source_33)s) THEN %(param_14)s WHEN (rpsl_objects.source = %(source_34)s) THEN %(param_15)s WHEN (rpsl_objects.source = %(source_35)s) THEN %(param_16)s WHEN (rpsl_objects.source = %(source_36)s) THEN
 %(param_17)s WHEN (rpsl_objects.source = %(source_37)s) THEN %(param_18)s WHEN (rpsl_objects.source = %(source_38)s) THEN %(param_19)s ELSE %(param_20)s END, rpsl_objects.ip_first ASC, rpsl_objects.asn_first ASC, rpsl_objects.rpsl_pk ASC]
2020-07-06 17:07:02,998 irrd[8682]: [irrd.server.whois.server#INFO] 2001:db8::2:40408: sent answer to query, elapsed 0.006789637729525566s, 58 bytes: !a4AS-ALTOPIA
```

This happens for many commands after a ```!!```: ```!a4```, ```!a6```, ```!a``` etc.

**IRRd version you are running**
ef416b24a8f1b6a3e82234c796a2dadc7ae52852

**Comment by mxsasha** [comment]
I can reproduce this. This is also definitely a bug in the tests :)

**Comment by ccaputo** [comment]
Confirmed.
