### ISSUE TITLE
FATAL:  remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by ccaputo** [irrdnet/irrd#350]
**Describe the bug**
Installed 074b757926dffb90eea416649526c0195885d83d and am testing with route server software that performs many consecutive queries:

```
2020-07-06 17:46:00,454 irrd[24338]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44146: processing query: !!
2020-07-06 17:46:00,454 irrd[24338]: [irrd.server.whois.server#INFO] 2001:db8::2:44146: sent answer to query, elapsed 3.271736204624176e-05s, 0 bytes: !!
2020-07-06 17:46:00,454 irrd[24338]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44146: processing query: !gas6391
2020-07-06 17:46:00,454 irrd[24338]: [irrd.server.whois.server#INFO] 2001:db8::2:44146: sent answer to query, elapsed 8.732080459594727e-05s, 71 bytes: !gas6391
2020-07-06 17:46:00,455 irrd[24338]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44146: processing query: !q
2020-07-06 17:46:00,455 irrd[24338]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44146: closed connection per request
2020-07-06 17:46:00,464 irrd[24340]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44148: processing query: !!
2020-07-06 17:46:00,465 irrd[24340]: [irrd.server.whois.server#INFO] 2001:db8::2:44148: sent answer to query, elapsed 2.7215108275413513e-05s, 0 bytes: !!
2020-07-06 17:46:00,465 irrd[24340]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44148: processing query: !6as6391
2020-07-06 17:46:00,465 irrd[24340]: [irrd.server.whois.server#INFO] 2001:db8::2:44148: sent answer to query, elapsed 7.623247802257538e-05s, 21 bytes: !6as6391
2020-07-06 17:46:00,465 irrd[24340]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44148: processing query: !q
2020-07-06 17:46:00,465 irrd[24340]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44148: closed connection per request
2020-07-06 17:46:00,476 irrd[24342]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44150: processing query: !!
2020-07-06 17:46:00,476 irrd[24342]: [irrd.server.whois.server#INFO] 2001:db8::2:44150: sent answer to query, elapsed 3.124214708805084e-05s, 0 bytes: !!
2020-07-06 17:46:00,476 irrd[24342]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44150: processing query: !gas6456
2020-07-06 17:46:00,476 irrd[24342]: [irrd.server.whois.server#INFO] 2001:db8::2:44150: sent answer to query, elapsed 9.584799408912659e-05s, 70 bytes: !gas6456
2020-07-06 17:46:00,477 irrd[24342]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44150: processing query: !q
2020-07-06 17:46:00,477 irrd[24342]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44150: closed connection per request
2020-07-06 17:46:00,487 irrd[24344]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44152: processing query: !!
2020-07-06 17:46:00,487 irrd[24344]: [irrd.server.whois.server#INFO] 2001:db8::2:44152: sent answer to query, elapsed 2.73045152425766e-05s, 0 bytes: !!
2020-07-06 17:46:00,487 irrd[24344]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44152: processing query: !6as6456
2020-07-06 17:46:00,487 irrd[24344]: [irrd.server.whois.server#INFO] 2001:db8::2:44152: sent answer to query, elapsed 0.00010089017450809479s, 22 bytes: !6as6456
2020-07-06 17:46:00,487 irrd[24344]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44152: processing query: !q
2020-07-06 17:46:00,487 irrd[24344]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44152: closed connection per request
2020-07-06 17:46:00,497 irrd[24346]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44154: processing query: !!
2020-07-06 17:46:00,497 irrd[24346]: [irrd.server.whois.server#INFO] 2001:db8::2:44154: sent answer to query, elapsed 3.3719465136528015e-05s, 0 bytes: !!
2020-07-06 17:46:00,498 irrd[24346]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44154: processing query: !gas6461
2020-07-06 17:46:00,498 irrd[24346]: [irrd.server.whois.server#INFO] 2001:db8::2:44154: sent answer to query, elapsed 0.00017400458455085754s, 1592 bytes: !gas6461
2020-07-06 17:46:00,498 irrd[24346]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44154: processing query: !q
2020-07-06 17:46:00,498 irrd[24346]: [irrd.server.whois.server#DEBUG] 2001:db8::2:44154: closed connection per request
2020-07-06 17:46:00,508 irrd[24348]: [irrd.server.whois.server#ERROR] Failed to handle whois connection, traceback follows: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections

(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/server.py", line 128, in run
    self.handle_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/server.py", line 164, in handle_connection
    self.query_parser = WhoisQueryParser(client_ip, self.client_str, self.preloader)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/query_parser.py", line 63, in __init__
    self.database_handler = DatabaseHandler()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/storage/database_handler.py", line 51, in __init__
    self._connection = get_engine().connect()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2272, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2379, in raw_connection
    self.pool.unique_connection, _connection
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2349, in _wrap_pool_connect
    e, dialect, self
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1591, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections

(Background on this error at: http://sqlalche.me/e/e3q8)
2020-07-06 17:46:00,611 irrd[24350]: [irrd.server.whois.server#ERROR] Failed to handle whois connection, traceback follows: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections

(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/server.py", line 128, in run
    self.handle_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/server.py", line 164, in handle_connection
    self.query_parser = WhoisQueryParser(client_ip, self.client_str, self.preloader)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/query_parser.py", line 63, in __init__
    self.database_handler = DatabaseHandler()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/storage/database_handler.py", line 51, in __init__
    self._connection = get_engine().connect()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2272, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2379, in raw_connection
    self.pool.unique_connection, _connection
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2349, in _wrap_pool_connect
    e, dialect, self
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1591, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections

(Background on this error at: http://sqlalche.me/e/e3q8)
2020-07-06 17:46:00,620 irrd[24352]: [irrd.server.whois.server#ERROR] Failed to handle whois connection, traceback follows: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections

(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/server.py", line 128, in run
    self.handle_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/server.py", line 164, in handle_connection
    self.query_parser = WhoisQueryParser(client_ip, self.client_str, self.preloader)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/server/whois/query_parser.py", line 63, in __init__
    self.database_handler = DatabaseHandler()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/irrd/storage/database_handler.py", line 51, in __init__
    self._connection = get_engine().connect()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2272, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2379, in raw_connection
    self.pool.unique_connection, _connection
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2349, in _wrap_pool_connect
    e, dialect, self
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1591, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/seaix/irrd-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections

(Background on this error at: http://sqlalche.me/e/e3q8)
2020-07-06 17:46:00,629 irrd[24354]: [irrd.server.whois.server#ERROR] Failed to handle whois connection, traceback follows: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections
[...]
```

**IRRd version you are running**
074b757926dffb90eea416649526c0195885d83d

**Comment by mxsasha** [comment]
What is your max_connections setting in PostgreSQL, and how many whois workers are you running (`server.whois.max_connections`)?

**Comment by ccaputo** [comment]
I have ```server.whois.max_connections``` set to 50 and postgresql.conf with ```max_connections = 100```.

**Comment by ccaputo** [comment]
I confirm postgres is issuing ```FATAL:  remaining connection slots are reserved for non-replication superuser connections``` and:

```
# ps auwx | grep postgres.*irrd | grep -v grep | wc -l
97

# pgrep -l postgres | wc -l
104

# pgrep -l irrd | wc -l
53
```

**Comment by mxsasha** [comment]
It looks like there is an IRRd bug here - looking into it. My own testing setup doesn't run 50 workers so I haven't run into this exact variation, but there is some bug here.

**Comment by ccaputo** [comment]
In case helpful: The script that triggers this is not concurrent, but rather just one bgpq4 process after another.

**Comment by ccaputo** [comment]
Fix confirmed.  Thanks!
