### ISSUE TITLE
NRTM updates failing - "UUID found"

### ISSUE THREAD

**Issue by dhutchin-ctl** [irrdnet/irrd#663]
I am now getting NRTM update failures for both the LEVEL3 IRR and RADB.  On every attempt to periodically updated via NRTM (15 minutes), I am getting a failure near what appears to be the end of the update:

2022-06-24 03:52:43,036 irrd[2454181]: [irrd.mirroring.mirror_runners_import#ERROR] An exception occurred while attempting a mirror update or initial import for RADB: sequence item 0: expected str, UUID found
Traceback (most recent call last):
  File "/export/home/irrd/.venv/lib/pypy3.9/site-packages/irrd/mirroring/mirror_runners_import.py", line 54, in run
    self.update_stream_runner.run(serial_newest_mirror, database_handler=self.database_handler)
  File "/export/home/irrd/.venv/lib/pypy3.9/site-packages/irrd/mirroring/mirror_runners_import.py", line 362, in run
    operation.save(database_handler)
  File "/export/home/irrd/.venv/lib/pypy3.9/site-packages/irrd/mirroring/nrtm_operation.py", line 81, in save
    database_handler.delete_rpsl_object(rpsl_object=obj, origin=JournalEntryOrigin.mirror,
  File "/export/home/irrd/.venv/lib/pypy3.9/site-packages/irrd/storage/database_handler.py", line 393, in delete_rpsl_object
    affected_pks = ','.join([r[0] for r in results.fetchall()])
TypeError: sequence item 0: expected str, UUID found

I just updated to IRRd V4.2.5, that did not fix the problem (nor did it change the behavior)

**Comment by troy2914** [comment]
This was fixed in 4.2.5 released yesterday.  Duplicate of #661

**Comment by dhutchin-ctl** [comment]
For RADB, I first saw this on May 3, but it ended on May 6.  Then LEVEL3 updates starting doing this on 6/21.  Then RADB started doing this again on 6/23 as the 00:49:33 update.
And correction to the above, restarting IRRd seems to have solved the problem for RADB (either that or the update to IRRd 4.2.5).  But the LEVEL3 updates started working an hour before the restart.

**Comment by dhutchin-ctl** [comment]
Troy says this is a duplicate of #661 and was fixed in the 4.2.5 release.
