### ISSUE TITLE
IRRd V4.2.5 stops handling whois requests

### ISSUE THREAD

**Issue by dhutchin-ctl** [irrdnet/irrd#701]
**Describe the bug**
I am experiencing repeated conditions where IRRd stops handling whois (port 43) requests. This is happening roughly daily.  It is resolved by restarting IRRd. 

**To Reproduce**
I don't have a definitive way to reproduce the problem.  I restarted irrd on 11/22 @ 14:16z.  As usual, we have a very high rate of queries to our IRR (not unexpected). Between 11/22 14:16z and 11/23 16:15z, there were 491428 queries.  As far as I know, all those queries were responded to, however, there were 996 instances of the following:

```
2022-11-23 16:15:36,120 irrd[2948]: [irrd.server.whois.server#ERROR] Failed to handle whois connection, traceback follows:                                     |probably due to a bug and you should report it.
Traceback (most recent call last):                                                                                                                             |
  File "/export/home/irrd/.venv/lib/pypy3.9/site-packages/irrd/server/whois/server.py", line 142, in run                                                       |You can disable the popping up of this buffer by adding the entry
    self.request, self.client_address = self.connection_queue.get()                                                                                            |(undo discard-info) to the user option `warning-suppress-types',
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/queues.py", line 122, in get                                               |which is defined in the `warnings' library.
    return _ForkingPickler.loads(res)                                                                                                                          |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/pickle.py", line 1785, in _loads                                                           |
    return _Unpickler(file, fix_imports=fix_imports, buffers=buffers,                                                                                          |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/pickle.py", line 1226, in load                                                             |
    dispatch[key[0]](self)                                                                                                                                     |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/pickle.py", line 1603, in load_reduce                                                      |
    stack[-1] = func(*args)                                                                                                                                    |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/reduction.py", line 246, in _rebuild_socket                                |
    fd = df.detach()                                                                                                                                           |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/resource_sharer.py", line 57, in detach                                    |
    with _resource_sharer.get_connection(self._id) as conn:                                                                                                    |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/resource_sharer.py", line 86, in get_connection                            |
    c = Client(address, authkey=process.current_process().authkey)                                                                                             |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/connection.py", line 513, in Client                                        |
    answer_challenge(c, authkey)                                                                                                                               |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/connection.py", line 757, in answer_challenge                              |
    message = connection.recv_bytes(256)         # reject large message                                                                                        |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/connection.py", line 221, in recv_bytes                                    |
    buf = self._recv_bytes(maxlength)                                                                                                                          |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/connection.py", line 419, in _recv_bytes                                   |
    buf = self._recv(4)                                                                                                                                        |
  File "/export/home/irrd/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/multiprocessing/connection.py", line 388, in _recv                                         |
    raise EOFError                                                                                                                                             |
EOFError

```
Including the last four instances of that traceback all at 11/23 16:15:44z.  I restarted IRRd at ~11/23 16:42 when I noticed that queries were hanging.

This has been a roughly daily event where the condition represents it self every 24 (+/- 4?) hours.

**Expected behaviour**

**IRRd version you are running**
4.2.5. on CentOS 7

**Additional context**

**Comment by dhutchin-ctl** [comment]
Possibly related to #649 and #693.  Waiting for #700 to test.  The above failure was using pypy3.9-7.3.9.

**Comment by dhutchin-ctl** [comment]
For what it is worth:  
server:
    http:
        workers: 8

    whois:
        max_connections: 8
 ------
CPU: 6
MemTotal: 48GB

**Comment by mxsasha** [comment]
Also may be relevant here: I just added a wiki page with additional debugging tips for these kind of issues: https://github.com/irrdnet/irrd/wiki/Debugging-and-reporting-tips-for-complex-issues

Regaring the EOFError, are you sure you aren't running out of memory? Would not expect it with 48GB, but it is apparently a possible case.

The number of functioning workers does not decrease? As you start out with 8, I assume with these query volumes you'd notice query failure pretty fast if all 8 broke completely.

**Comment by dhutchin-ctl** [comment]
It does not appear that the number of functioning workers is diminishing. And I have not caught a memory exhaustion situation. However, I have discovered a situation where irrd is writing a huge number of messages to /var/log/mail (instead of the IRRD log).  But with regard to the tips for complex issues....

OS: CentOS 8
IRRD: 4.2.5
Python:
Python 3.9.12 (05fbe3aa5b0845e6c37239768aa455451aa5faba, Mar 29 2022, 08:15:34)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]

See attached irrd.yaml:
[irrd.yaml.gz](https://github.com/irrdnet/irrd/files/10126287/irrd.yaml.gz)


PostgreSQL:
Version      : 10.21
Release      : 2.module+el8.6.0+15342+53518fac
Architecture : x86_64
Size         : 5.5 M

Redis:
Version      : 5.0.3
Release      : 5.module+el8.4.0+12927+b9845322
Architecture : x86_64
Size         : 3.2 M

MemTotal:       49241744 kB
MemFree:        10298580 kB
MemAvailable:   28020856 kB

SwapTotal:       3145724 kB
SwapFree:        2988344 kB

CPUs: 6
(see attached cpuinfo.gz)
[cpuinfo.gz](https://github.com/irrdnet/irrd/files/10126277/cpuinfo.gz)


There are whois queries on port 43 to the tune of 500,000 to 1,000,000 a day.
Queries seem to be only one per connection. Most of the queries are coming from
one internal source (I'm trying to get that shutdown, but....), so they are sequential/serial.

There ARE queries to graphQL, but not large numbers.  ~10/hour

There ARE authoritative changes being submitted, but not large numbers, ~5/hour

Postgres:
For the most part, logs are empty, with occasional spikes with lots of the following lines:
2022-11-27 06:11:30.149 GMT [2693887] LOG:  checkpoints are occurring too frequently (8 seconds apart)
2022-11-27 06:11:30.149 GMT [2693887] HINT:  Consider increasing the configuration parameter "max_wal_size".

Irrd log: see accompanying gzipped file
[irrd.log.gz](https://github.com/irrdnet/irrd/files/10126279/irrd.log.gz)


Kernel logs: see accompanying gzipped file
[varlogmessages.gz](https://github.com/irrdnet/irrd/files/10126284/varlogmessages.gz)

see attached sockstate.gz:
[sockstate.gz](https://github.com/irrdnet/irrd/files/10126289/sockstate.gz)

**Comment by dhutchin-ctl** [comment]
(sigh) I hate being a newbie at Python.  .pyc files were owned by root and were old.  Once they were deleted,  the whois query and logging problems seem to have gone away.

**Comment by dhutchin-ctl** [comment]
24 hours later, still good.

**Comment by mxsasha** [comment]
> (sigh) I hate being a newbie at Python. .pyc files were owned by root and were old. Once they were deleted, the whois query and logging problems seem to have gone away.

Oh, great find! That isn't really about being a Python newbie - it had not occurred to me that this could be the issue, I've certainly not heard it before.
