### ISSUE TITLE
IRRd 4.3.0 fails to start when run

### ISSUE THREAD

**Issue by ma-anazawa** [irrdnet/irrd#810]
I am trying to upgrade to 4.3.0 in a test environment.
When I start irrd, I get the following message.
Do you know the cause?
```
$ systemctl status irrd
● irrd.service - IRRD4 Service
   Loaded: loaded (/usr/lib/systemd/system/irrd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2023-07-05 15:55:31 JST; 5s ago
 Main PID: 390401 (irrd)
    Tasks: 4 (limit: 307810)
   Memory: 233.2M
   CGroup: /system.slice/irrd.service
           tq390401 /home/irrd/irrd-venv/bin/python3.7 /home/irrd/irrd-venv/bin/irrd --foreground --config=/home/i>
           tq390407 irrd-preload-store-manager
           mq390410 irrd-RPSLMirrorImportUpdateRunner-RADB

 7月 05 15:55:31 irrd1.jpix.ad.jp systemd[1]: Started IRRD4 Service.
 7月 05 15:55:32 irrd1.jpix.ad.jp irrd[390401]: Exception ignored in: <function _releaseLock at 0x7f601facb950>
 7月 05 15:55:32 irrd1.jpix.ad.jp irrd[390401]: Traceback (most recent call last):
 7月 05 15:55:32 irrd1.jpix.ad.jp irrd[390401]:   File "/usr/local/lib/python3.7/logging/__init__.py", line 221, i>
 7月 05 15:55:32 irrd1.jpix.ad.jp irrd[390401]:     def _releaseLock():
 7月 05 15:55:32 irrd1.jpix.ad.jp irrd[390401]:   File "/home/irrd/irrd-venv/lib/python3.7/site-packages/daemon/da>
 7月 05 15:55:32 irrd1.jpix.ad.jp irrd[390401]:     raise exception
 7月 05 15:55:32 irrd1.jpix.ad.jp irrd[390401]: SystemExit: Terminating on signal 15
```
```
$ tail -f /var/log/irrd/irrd.log
2023-07-05 05:26:22,626 irrd[333570]: [root#INFO] Starting preload store manager
2023-07-05 05:26:22,624 irrd[333569]: [irrd.utils.process_support#CRITICAL] Essential IRRd subprocess encountered a fatal error, traceback follows, shutting down: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/home/irrd/irrd-venv/lib/python3.7/site-packages/irrd/utils/process_support.py", line 21, in run
    super().run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/irrd/irrd-venv/lib/python3.7/site-packages/irrd/server/whois/server.py", line 38, in start_whois_server
    gid=gid,
  File "/home/irrd/irrd-venv/lib/python3.7/site-packages/irrd/server/whois/server.py", line 73, in __init__
    super().__init__(server_address, None, bind_and_activate)
  File "/usr/local/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
2023-07-05 05:26:22,627 irrd[333566]: [PidFile#DEBUG] <pid.posix.PidFile object at 0x7f2ced43c460> closing pidfile: /home/irrd/irrd.pid
2023-07-05 05:26:22,628 irrd[333566]: [PidFile#DEBUG] <pid.posix.PidFile object at 0x7f2ced43c460> closing pidfile: /home/irrd/irrd.pid
2023-07-05 05:26:22,632 irrd[333571]: [uvicorn.error#ERROR] [Errno 13] Permission denied
2023-07-05 05:26:22,735 irrd[333570]: [irrd.storage.preload#DEBUG] Starting preload store update from thread <PreloadUpdater(Thread-1, started daemon 139830924359424)>
2023-07-05 05:27:04,573 irrd[333570]: [irrd.storage.preload#INFO] Completed updating preload store from thread <PreloadUpdater(Thread-1, started daemon 139830924359424)>
```
```
$ cat /home/irrd/irrd.yaml
irrd:
    database_url: 'postgresql://irrd:irrd@localhost:5432/irrd'
    redis_url: 'unix:///var/run/redis/redis.sock'
    piddir: /home/irrd/

    access_lists:
        http_database_status:
            - '127.0.0.1'
            - '192.168.0.0/16'

    server:
        http:
            status_access_list: http_database_status
            interface: '::0'
            port: 80
        whois:
            interface: '::0'
            max_connections: 10
            port: 43

    compatibility:
        inetnum_search_disabled: true

    auth:
        gnupg_keyring: /home/irrd/gnupg-keyring/

    email:
        from: example@example.com
        smtp: localhost

    log:
        logfile_path: /var/log/irrd/irrd.log
        level: DEBUG

    rpki:
        roa_source: null

    sources_default:
        - RADB

    sources:
        RADB:
            authoritative: false
            keep_journal: true
            import_serial_source: 'ftp://ftp.radb.net/radb/dbase/RADB.CURRENTSERIAL'
            import_source: 'ftp://ftp.radb.net/radb/dbase/radb.db.gz'
            import_timer: 3600
            nrtm_host: whois.radb.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
```
**execution environment**
```
CentOS Linux release 8.2.2004 (Core)
Python 3.7.7
postgres (PostgreSQL) 10.14
Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=28849dbea6f07cc8
```

**Comment by MattKobayashi** [comment]
It looks like you're starting the daemon as a non-privileged user, which is preventing IRRd from binding to the port(s) it needs. If you want to run IRRd as a non-privileged user, you should configure the `user` and `group` settings in the config file and start the daemon as root. It will drop privileges once it's completed any tasks it needs to complete as root. More info here: https://irrd.readthedocs.io/en/stable/admins/deployment/#running-as-a-non-privileged-user

**Comment by mxsasha** [comment]
Yes, what Matt describes is exactly the issue. Specifically the whois port. Either set it to a non-privileged port, with port forwarding, or use user/group settings to drop privileges. A third option is to use setcap to allow your Python binary to bind to privileged ports, but this of course allows any Python code to then do this.
