### ISSUE TITLE
Refresh the db connection for the NRTM stream when seeing errors

### ISSUE THREAD

**Issue by Justin-APNIC** [irrdnet/irrd#892]
**Is your feature request related to a problem? Please describe.**
I got this error when my NRTM client sends a query to the IRRD.

```
2024-01-11 22:35:16,750 irrd[19]: [irrd.server.whois.server#DEBUG] ::ffff:10.2.87.244:59452: processing query: -g JPNIC:3:57325611-LAST -k
2024-01-11 22:35:16,762 irrd[19]: [irrd.server.whois.query_parser#ERROR] An exception occurred while processing whois query "-g JPNIC:3:57325611-LAST -k": (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT database_status.pk, database_status.source, database_status.serial_oldest_seen, database_status.serial_newest_seen, database_status.serial_oldest_journal, database_status.serial_newest_journal, database_status.serial_last_export, database_status.serial_newest_mirror, database_status.force_reload, database_status.synchronised_serials, database_status.last_error, database_status.last_error_timestamp, database_status.created, database_status.updated 
FROM database_status 
WHERE database_status.source IN (%(source_1)s) ORDER BY CASE WHEN (database_status.source = %(source_2)s) THEN %(param_1)s ELSE %(param_2)s END, database_status.source ASC]
[parameters: {'source_1': 'JPNIC', 'source_2': 'JPNIC', 'param_1': 1, 'param_2': 100000}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/irrd/server/whois/query_parser.py", line 99, in handle_query
    return self.handle_ripe_command(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/irrd/server/whois/query_parser.py", line 435, in handle_ripe_command
    result = self.handle_nrtm_request(components.pop(0))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/irrd/server/whois/query_parser.py", line 577, in handle_nrtm_request
    return NRTMGenerator().generate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/irrd/mirroring/nrtm_generator.py", line 36, in generate
    status = next(database_handler.execute_query(q))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/irrd/storage/database_handler.py", line 228, in execute_query
    raise exc
  File "/usr/local/lib/python3.11/site-packages/irrd/storage/database_handler.py", line 222, in execute_query
    result = execute_query()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/irrd/storage/database_handler.py", line 219, in execute_query
    return self._connection.execute(statement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
By looking at the PostgreSQL logs, nothing related to this issue. I can still see the idle in the pg_stat_activity table.
```
datid            | 16385
datname          | irrd
pid              | 251463
leader_pid       |
usesysid         | 16384
usename          | irrd
application_name |
client_addr      | 10.2.70.51
client_hostname  |
client_port      | 55690
backend_start    | 2024-01-12 10:05:28.016857+10
xact_start       | 2024-01-12 10:05:28.021032+10
query_start      | 2024-01-12 10:05:28.021548+10
state_change     | 2024-01-12 10:05:28.023068+10
wait_event_type  | Client
wait_event       | ClientRead
state            | idle in transaction
backend_xid      |
backend_xmin     |
query            | SELECT database_status.pk, database_status.source, database_status.serial_oldest_seen, database_status.seria
l_newest_seen, database_status.serial_oldest_journal, database_status.serial_newest_journal, database_status.serial_last_export
, database_status.serial_newest_mirror, database_status.force_reload, database_status.synchronised_serials, database_status.las
t_error, database_status.last_error_timestamp, database_status.created, database_status.updated +
                 | FROM database_status


                                                                                                +
                 | WHERE database_status.source IN ('JPNIC') ORDER BY CASE WHEN (database_status.source = 'JPNIC') THEN 1 ELSE
100000 END, database_status.source ASC
backend_type     | client backend 
```

By investigating this issue deeply, the dead connection may be caused by the network components like firewalls. Changing config for the tcp_keepalive_idle in the db seems resolve the issue.

**Describe the solution you'd like**
Can we enable the `refresh_on_error` when executing the query in the `NRTMGenerator` class which is `False` as default? e.g.
`database_handler.execute_query(query, refresh_on_error=True)
`
```
        for operation in database_handler.execute_query(q):
            operation_str = operation["operation"].value
            if version == "3":
                operation_str += " " + str(operation["serial_nrtm"])
            text = operation["object_text"]
            if remove_auth_hashes:
                text = remove_auth_hashes_func(text)
            operation_str += "\n\n" + text
            output.append(operation_str)
```

Also, why we don't enable the refresh_on_error in NRTMGenerator class? Any intentions for this?

The connection may be dropped off by other unknown reasons as well when processing the NRTM query. I think it is good to enable this refresh function in NRTMGenerator instead of raising the exception directly.

**Comment by mxsasha** [comment]
Thanks for investigating. Yes, we should use it here: the intended use is when we have very long lived DB connections, which work most of the time, but it's possible we don't notice a server restart until we try a query. This is done in the query handling, to avoid the latency of a new database connection. Other DB queries in query processing already use it, it's an oversight it was not used here.
